# mkVerbPlugin — build a complete, self-contained Claude Code plugin from verbspec registries.
#
# The output is a read-only store path that is simultaneously a marketplace and the plugin it
# lists, so it can be handed straight to `claude plugin marketplace add <store-path>` (verified:
# Claude Code neither writes to nor git-pulls a directory marketplace). Nothing points back at a
# working checkout, which is what made the hand-written plugin impossible to distribute.
#
#   $out/.claude-plugin/marketplace.json
#   $out/<name>/.claude-plugin/plugin.json
#   $out/<name>/.mcp.json          -> $out/<name>/bin/<name>-mcp   (absolute)
#   $out/<name>/commands/*.md      generated from each verb's summary
#   $out/<name>/bin/<name>-mcp     store-pinned bun launcher
#   $out/<name>/lib/mcp.js         the bundle
#   $out/<name>/<assets>           see ASSET LAYOUT below
#
# ASSET LAYOUT. Registry code commonly reads data files with
# `new URL("../HANDBOOK.md", import.meta.url)`. That is module-relative, so after bundling it
# resolves against the BUNDLE, not the original source file. Putting the bundle at `<name>/lib/`
# and the assets at `<name>/` reproduces the `src/` + repo-root layout the source was written
# against, so those reads keep working with zero source changes.
#
# HERMETICITY. `bun build` runs with no network, so the consumer's `src` must carry its own
# `node_modules` (machine-spec commits them, which is what makes this work). `--compile` is
# deliberately not used: bun's single-binary step hangs at 100% CPU under a nix build user on
# darwin. Bundle + store-pinned launcher gives the same closed-over property without the bug.

{ pkgs, routerSrc }:

{ name # plugin name; also the MCP server name and the /<name>:* command namespace
, version
, description
, owner # { name = "..."; }
, src # consumer source tree, including its node_modules
, registries # [ { path = "src/registry.ts"; export ? "registry"; id ? null; } ]
, assets ? [ ] # paths relative to `src`, copied to $out/<name>/
, marketplaceName ? name
, bun ? pkgs.bun
}:

let
  inherit (pkgs.lib) concatStringsSep imap0 optionalString escapeShellArg;

  # Each registry is imported from the generated sources.ts, which sits one level below the
  # consumer root at .verb-router/ — hence the "../" prefix on every declared path.
  importLine = i: r:
    let export = r.export or "registry";
    in ''import { ${export} as r${toString i} } from "../${r.path}";'';

  sourceEntry = i: r:
    let ns = r.id or null;
    in "  { ${optionalString (ns != null) ''id: "${ns}", ''}registry: r${toString i} },";

  sourcesTs = ''
    // GENERATED by mkVerbPlugin.nix — do not edit.
    ${concatStringsSep "\n" (imap0 importLine registries)}

    export const sources = [
    ${concatStringsSep "\n" (imap0 sourceEntry registries)}
    ];

    export const meta = { name: "${name}", version: "${version}" };
  '';

  launcherName = "${name}-mcp";
in
pkgs.runCommand "${name}-plugin-${version}"
{
  nativeBuildInputs = [ bun ];
  passthru = { inherit name version marketplaceName; };
  meta = {
    inherit description;
    mainProgram = launcherName;
  };
} ''
  set -euo pipefail
  export HOME=$TMPDIR

  # 1. Reproduce the consumer tree so bun resolves its committed node_modules by walking up.
  build=$TMPDIR/build
  mkdir -p "$build"
  cp -R ${src}/. "$build/"
  chmod -R u+w "$build"

  # 2. Drop the router in one level below the root, so "../<path>" reaches the consumer's src
  #    and module resolution still finds node_modules above it.
  mkdir -p "$build/.verb-router"
  cp ${routerSrc}/*.ts "$build/.verb-router/"
  cat > "$build/.verb-router/sources.ts" <<'SOURCES_EOF'
  ${sourcesTs}
  SOURCES_EOF

  pluginDir=$out/${name}
  mkdir -p "$pluginDir/lib" "$pluginDir/bin"

  # 3. Bundle. 700+ modules collapse to one file with no runtime node_modules.
  bun build "$build/.verb-router/entry.ts" --target=bun --outfile "$pluginDir/lib/mcp.js"

  # 4. Assets alongside lib/, so module-relative "../x" reads resolve (see ASSET LAYOUT).
  ${concatStringsSep "\n" (map (a: ''
    cp -R ${escapeShellArg "${src}/${a}"} "$pluginDir/"
  '') assets)}

  # 5. Store-pinned launcher — the absolute command .mcp.json will name.
  cat > "$pluginDir/bin/${launcherName}" <<LAUNCHER_EOF
  #!/bin/sh
  exec ${bun}/bin/bun run "$pluginDir/lib/mcp.js" "\$@"
  LAUNCHER_EOF
  chmod +x "$pluginDir/bin/${launcherName}"

  # 6. Generate commands + manifests from the merged registry. Runs in the build tree because it
  #    imports the registries; a collision or an empty registry fails the derivation here.
  cd "$build"
  OUT=$out \
  PLUGIN_NAME=${name} \
  PLUGIN_VERSION=${version} \
  PLUGIN_DESCRIPTION=${escapeShellArg description} \
  MARKETPLACE_NAME=${marketplaceName} \
  OWNER_NAME=${escapeShellArg owner.name} \
  SERVER_LAUNCHER="$pluginDir/bin/${launcherName}" \
    bun run "$build/.verb-router/gen.ts"
''
