#!/usr/bin/env bun
// The MCP server entrypoint that gets bundled into the plugin.
//
// Deliberately trivial: `sources.ts` is generated by mkVerbPlugin.nix from the registries the
// caller declared, so this file is identical in every build and carries no per-machine detail.

import { serve } from "./router.ts";
import { meta, sources } from "./sources.ts";

await serve(sources, meta);
